version: "3.8"

services:
  backend:
    image: namhyunsik/finance-model-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env # .env 파일에서 환경변수 로드
    restart: unless-stopped

  frontend:
    image: namhyunsik/finance-model-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
